name: AdvancedVanilla
version: '${version}'
main: greenlink.advancedvanilla.AdvancedVanilla
api-version: 1.19
softdepend: ["PlaceholderAPI"]
commands:
  profile:
    usage: ''
  compass:
    usage: ''
  changelog:
    usage: ''
